name: pgraft-build-rocky-pg-18

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
    
    steps:
      - name: Install git
        run: |
          dnf install -y git

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update DNF cache
        run: |
          dnf clean all
          dnf makecache --refresh || dnf makecache

      - name: Install EPEL repository and enable CRB
        run: |
          dnf install -y epel-release
          dnf config-manager --set-enabled crb || /usr/bin/crb enable

      - name: Install build dependencies
        run: |
          dnf install -y \
            gcc \
            make \
            wget \
            gnupg2 \
            perl

      - name: Install perl-IPC-Run from EPEL
        run: |
          dnf install -y perl-IPC-Run

      - name: Install PostgreSQL 18
        run: |
          dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
          dnf -qy module disable postgresql
          dnf install -y postgresql18 postgresql18-server postgresql18-devel || {
            echo "PostgreSQL 18 not available yet, falling back to PostgreSQL 17"
            dnf install -y postgresql17 postgresql17-server postgresql17-devel
          }

      - name: Detect PostgreSQL paths
        run: |
          PG_CONFIG=$(find /usr -name pg_config -path "*/pgsql-18/*" | head -1)
          PG_BINDIR=$(dirname ${PG_CONFIG})
          PG_LIBDIR=$(${PG_CONFIG} --libdir)
          PG_PREFIX=$(dirname ${PG_BINDIR})
          
          echo "PG_CONFIG=${PG_CONFIG}" >> $GITHUB_ENV
          echo "PG_BINDIR=${PG_BINDIR}" >> $GITHUB_ENV
          echo "PG_LIBDIR=${PG_LIBDIR}" >> $GITHUB_ENV
          echo "PG_PREFIX=${PG_PREFIX}" >> $GITHUB_ENV
          
          echo "Detected PostgreSQL 18 paths:"
          echo "  PG_CONFIG = ${PG_CONFIG}"

      - name: Install Go
        run: |
          wget https://go.dev/dl/go1.23.4.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Set up build environment
        run: |
          PG_INCLUDEDIR=$(${PG_CONFIG} --includedir)
          PG_INCLUDEDIR_SERVER=$(${PG_CONFIG} --includedir-server)
          
          echo "CGO_CFLAGS=-I${PG_INCLUDEDIR} -I${PG_INCLUDEDIR_SERVER} -I/usr/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L${PG_LIBDIR}" >> $GITHUB_ENV
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "PATH=${PG_BINDIR}:/usr/local/go/bin:$PATH" >> $GITHUB_ENV

      - name: Download Go dependencies
        run: |
          cd src
          /usr/local/go/bin/go mod download
          /usr/local/go/bin/go mod verify

      - name: Show Makefile being used
        run: |
          echo "Using Makefile.rocky with PG_CONFIG=${PG_CONFIG}"
          head -20 Makefile.rocky

      - name: Build pgraft
        run: |
          # Use Rocky-specific Makefile
          export PATH=${PG_BINDIR}:/usr/local/go/bin:$PATH
          make -f Makefile.rocky PG_CONFIG=${PG_CONFIG} clean || true
          make -f Makefile.rocky PG_CONFIG=${PG_CONFIG} all 2>&1 | tee build.log

      - name: Verify build output
        run: |
          if [ -f pgraft.so ]; then
            echo "✓ Build successful: pgraft.so"
            ls -lh pgraft.so
          else
            echo "✗ Build failed"
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pgraft-rocky-pg18
          path: |
            pgraft.so
            src/pgraft_go.so
            pgraft.control
            pgraft--1.0.sql

