name: pgraft-build-rocky-pg-17

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
    
    steps:
      - name: Install git
        run: |
          dnf install -y git

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update DNF cache
        run: |
          dnf clean all
          dnf makecache --refresh || dnf makecache

      - name: Install EPEL repository and enable CRB
        run: |
          dnf install -y epel-release
          dnf config-manager --set-enabled crb || /usr/bin/crb enable

      - name: Install build dependencies
        run: |
          dnf install -y \
            gcc \
            make \
            wget \
            gnupg2 \
            perl

      - name: Install perl-IPC-Run from EPEL
        run: |
          dnf install -y perl-IPC-Run

      - name: Install PostgreSQL 17
        run: |
          dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
          dnf -qy module disable postgresql
          dnf install -y postgresql17 postgresql17-server postgresql17-devel

      - name: Detect PostgreSQL paths
        run: |
          # Find pg_config (Rocky puts it in /usr/pgsql-17/bin/)
          PG_CONFIG=$(find /usr -name pg_config -path "*/pgsql-17/*" | head -1)
          PG_BINDIR=$(dirname ${PG_CONFIG})
          PG_LIBDIR=$(${PG_CONFIG} --libdir)
          PG_PREFIX=$(dirname ${PG_BINDIR})
          
          echo "PG_CONFIG=${PG_CONFIG}" >> $GITHUB_ENV
          echo "PG_BINDIR=${PG_BINDIR}" >> $GITHUB_ENV
          echo "PG_LIBDIR=${PG_LIBDIR}" >> $GITHUB_ENV
          echo "PG_PREFIX=${PG_PREFIX}" >> $GITHUB_ENV
          
          echo "Detected PostgreSQL paths:"
          echo "  PG_CONFIG = ${PG_CONFIG}"
          echo "  PG_PREFIX = ${PG_PREFIX}"
          echo "  PG_BINDIR = ${PG_BINDIR}"
          echo "  PG_LIBDIR = ${PG_LIBDIR}"

      - name: Verify PostgreSQL installation
        run: |
          ${PG_CONFIG} --version
          ${PG_CONFIG} --includedir
          ${PG_CONFIG} --libdir

      - name: Install Go
        run: |
          wget https://go.dev/dl/go1.23.4.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Verify Go installation
        run: |
          /usr/local/go/bin/go version

      - name: Set up build environment
        run: |
          PG_INCLUDEDIR=$(${PG_CONFIG} --includedir)
          PG_INCLUDEDIR_SERVER=$(${PG_CONFIG} --includedir-server)
          
          echo "CGO_CFLAGS=-I${PG_INCLUDEDIR} -I${PG_INCLUDEDIR_SERVER} -I/usr/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L${PG_LIBDIR}" >> $GITHUB_ENV
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "PATH=${PG_BINDIR}:/usr/local/go/bin:$PATH" >> $GITHUB_ENV

      - name: Download Go dependencies
        run: |
          cd src
          /usr/local/go/bin/go mod download
          /usr/local/go/bin/go mod verify

      - name: Patch Makefile for Rocky Linux
        run: |
          cp Makefile Makefile.original
          
          # Replace hardcoded paths with detected paths
          sed -i "s|PG_CONFIG = /usr/local/pgsql.17/bin/pg_config|PG_CONFIG = ${PG_CONFIG}|g" Makefile
          sed -i "s|/usr/local/pgsql.17/lib|${PG_LIBDIR}|g" Makefile
          sed -i 's|pgraft_go.dylib|pgraft_go.so|g' Makefile
          
          echo "Detected paths:"
          echo "  PG_CONFIG = ${PG_CONFIG}"
          echo "  PG_LIBDIR = ${PG_LIBDIR}"
          echo ""
          echo "Makefile changes:"
          diff -u Makefile.original Makefile || true

      - name: Build pgraft
        run: |
          export PATH=${PG_BINDIR}:/usr/local/go/bin:$PATH
          make clean || true
          make all 2>&1 | tee build.log

      - name: Verify build output
        run: |
          if [ -f pgraft.so ]; then
            echo "✓ Build successful: pgraft.so"
            ls -lh pgraft.so
            file pgraft.so
          else
            echo "✗ Build failed: pgraft.so not found"
            exit 1
          fi
          
          if [ -f src/pgraft_go.so ]; then
            echo "✓ Go library built: pgraft_go.so"
            ls -lh src/pgraft_go.so
          fi

      - name: Check for warnings
        run: |
          if grep -i "warning:" build.log; then
            echo "⚠ Warnings found in build"
          else
            echo "✓ No warnings"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pgraft-rocky-pg17
          path: |
            pgraft.so
            src/pgraft_go.so
            pgraft.control
            pgraft--1.0.sql

