name: pgraft-build-ubuntu-pg-16

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc \
            make \
            wget \
            gnupg \
            ca-certificates

      - name: Install PostgreSQL 16
        run: |
          echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y postgresql-16 postgresql-server-dev-16

      - name: Detect PostgreSQL paths
        run: |
          PG_CONFIG=$(which pg_config || find /usr -name pg_config -path "*/16/*" | head -1)
          PG_BINDIR=$(dirname ${PG_CONFIG})
          PG_LIBDIR=$(${PG_CONFIG} --libdir)
          PG_PREFIX=$(dirname ${PG_BINDIR})
          
          echo "PG_CONFIG=${PG_CONFIG}" >> $GITHUB_ENV
          echo "PG_BINDIR=${PG_BINDIR}" >> $GITHUB_ENV
          echo "PG_LIBDIR=${PG_LIBDIR}" >> $GITHUB_ENV
          echo "PG_PREFIX=${PG_PREFIX}" >> $GITHUB_ENV
          
          echo "Detected PostgreSQL 16 paths:"
          echo "  PG_CONFIG = ${PG_CONFIG}"
          echo "  PG_PREFIX = ${PG_PREFIX}"

      - name: Verify PostgreSQL installation
        run: |
          ${PG_CONFIG} --version
          ${PG_CONFIG} --includedir
          ${PG_CONFIG} --libdir

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up build environment
        run: |
          PG_INCLUDEDIR=$(${PG_CONFIG} --includedir)
          PG_INCLUDEDIR_SERVER=$(${PG_CONFIG} --includedir-server)
          
          echo "CGO_CFLAGS=-I${PG_INCLUDEDIR} -I${PG_INCLUDEDIR_SERVER}" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L${PG_LIBDIR}" >> $GITHUB_ENV
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "${PG_BINDIR}" >> $GITHUB_PATH

      - name: Download Go dependencies
        run: |
          cd src
          go mod download
          go mod verify

      - name: Show Makefile being used
        run: |
          echo "Using Makefile.ubuntu with PG_CONFIG=${PG_CONFIG}"
          head -20 Makefile.ubuntu

      - name: Build pgraft
        run: |
          # Use Ubuntu-specific Makefile
          make -f Makefile.ubuntu PG_CONFIG=${PG_CONFIG} clean || true
          make -f Makefile.ubuntu PG_CONFIG=${PG_CONFIG} all 2>&1 | tee build.log

      - name: Verify build output
        run: |
          if [ -f pgraft.so ]; then
            echo "✓ Build successful: pgraft.so"
            ls -lh pgraft.so
            file pgraft.so
          else
            echo "✗ Build failed: pgraft.so not found"
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pgraft-ubuntu-pg16
          path: |
            pgraft.so
            src/pgraft_go.so
            pgraft.control
            pgraft--1.0.sql

